# Generated by Django 5.0.6 on 2024-08-26 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_ratingcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingcomment',
            options={'ordering': ['-time_create'], 'verbose_name': 'Рейтинг комментария', 'verbose_name_plural': 'Рейтинг комментариев'},
        ),
    ]
