# Generated by Django 5.0.6 on 2024-08-26 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_ratingcomment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratingcomment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentsratings', to='blog.comment', verbose_name='Комментарий'),
        ),
    ]
