# Generated by Django 5.0.6 on 2024-08-26 14:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_ratingcomment_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=ckeditor.fields.RichTextField(max_length=1000, verbose_name='Полный текст записи'),
        ),
    ]
