# Generated by Django 5.0.6 on 2024-08-28 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_post_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Тема сообщения')),
                ('message', models.TextField(max_length=500, verbose_name='Текст сообщения')),
                ('date_time', models.DateTimeField(verbose_name='Время отправки')),
            ],
        ),
        migrations.AlterModelOptions(
            name='ratingcomment',
            options={'verbose_name': 'Личное сообщение', 'verbose_name_plural': 'Личные сообщения'},
        ),
        migrations.RemoveIndex(
            model_name='ratingcomment',
            name='blog_rating_time_cr_94ddbc_idx',
        ),
        migrations.AlterUniqueTogether(
            name='ratingcomment',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, max_length=300, verbose_name='Описание категории'),
        ),
        migrations.AddField(
            model_name='privatemessages',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL, verbose_name='Получатель'),
        ),
        migrations.AddField(
            model_name='privatemessages',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель'),
        ),
    ]
