# Generated by Django 5.0.6 on 2024-08-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_privatemessages_alter_ratingcomment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatemessages',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='privatemessages',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время отправки'),
        ),
        migrations.AlterField(
            model_name='privatemessages',
            name='message',
            field=models.TextField(verbose_name='Текст сообщения'),
        ),
    ]
