# Generated by Django 5.0.6 on 2024-08-28 07:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_privatemessages_is_read_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privatemessages',
            options={'verbose_name': 'Личное сообщение', 'verbose_name_plural': 'Личные сообщения'},
        ),
        migrations.AlterModelOptions(
            name='ratingcomment',
            options={'ordering': ['-time_create'], 'verbose_name': 'Рейтинг комментария', 'verbose_name_plural': 'Рейтинг комментариев'},
        ),
        migrations.AlterUniqueTogether(
            name='ratingcomment',
            unique_together={('comment', 'ip_address')},
        ),
        migrations.AddIndex(
            model_name='ratingcomment',
            index=models.Index(fields=['-time_create', 'value'], name='blog_rating_time_cr_94ddbc_idx'),
        ),
    ]
