# Generated by Django 5.0.6 on 2024-08-29 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_privatemessages_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateMessages',
        ),
    ]
