# Generated by Django 5.0.6 on 2024-09-03 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('privatemessages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='privatemessages',
            options={'ordering': ['date_time'], 'verbose_name': 'Личное сообщение', 'verbose_name_plural': 'Личные сообщения'},
        ),
        migrations.RemoveField(
            model_name='privatemessages',
            name='title',
        ),
    ]
